version: 2.1
orbs:
  python: circleci/python@2.0.3
  circleci-cli: circleci/circleci-cli@0.1.9
commands:
  setup-artifactory:
    steps:
      - run:
          name: Configure poetry to pull from artifactory
          command: |
            poetry config repositories.leapyear "$ARTIFACTORY_URL/api/pypi/leapyear-pypi-all/simple"
            poetry config http-basic.leapyear "$ARTIFACTORY_USER" "$ARTIFACTORY_PASSWORD"
jobs:
  lint:
    executor: python/default
    steps:
      - setup-artifactory
      - circleci-cli/install
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          args: -E prospector -E flake8
      - run:
          name: Bootstrap the linters
          command: poetry run lint --bootstrap
      - run:
          name: Create the pre-commit cache key
          command: python --version --version | cat .pre-commit-config.yaml - > pre-commit-cache-key.txt
      - restore_cache:
          keys:
            - v1-pre-commit-cache-{{ checksum "pre-commit-cache-key.txt" }}
      - run:
          name: Run all of the linters
          command: poetry run pre-commit run -av
          environment:
            SKIP: no-commit-to-branch
      - save_cache:
          key: v1-pre-commit-cache-{{ checksum "pre-commit-cache-key.txt" }}
          paths:
            - ~/.cache/pre-commit
  behave:
    executor: python/default
    steps:
      - setup-artifactory
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          args: -E prospector -E flake8
      - run:
          name: behave tests
          command: poetry run behave
  deploy:
    executor: python/default
    steps:
      - setup-artifactory
      - checkout
      - run:
          name: Determine the maturity of the artifact based on context clues
          command: |
            ARTIFACTORY_MATURITY=scratch
            if [[ -n "${CIRCLE_TAG:-}" ]]; then
              # tagged versions are releases
              ARTIFACTORY_MATURITY=release
            elif [[ "${CIRCLE_BRANCH}" == main ]]; then
              # untagged on main
              ARTIFACTORY_MATURITY=snapshot
            fi
            echo "export ARTIFACTORY_MATURITY=\"${ARTIFACTORY_MATURITY}\"" >> $BASH_ENV
      - run:
          name: Determine the correct repo based on context clues
          command: |
            ARTIFACTORY_REPO=leapyear-bin-${ARTIFACTORY_MATURITY}-local
            echo "export ARTIFACTORY_REPO=\"${ARTIFACTORY_REPO}\"" >> $BASH_ENV
      - run:
          name: Configure poetry to push to pypi
          command: |
            poetry config repositories.leapyear-artifactory ${ARTIFACTORY_URL}/api/pypi/leapyear-pypi-${ARTIFACTORY_MATURITY}-local
            poetry config http-basic.leapyear-artifactory $ARTIFACTORY_USER $ARTIFACTORY_PASSWORD
      - run:
          name: Determine the version of the artifact
          command: |
            mkdir -p dist
            if [[ -n "${CIRCLE_TAG:-}" ]]
            then
              # This is tagged, so construct the version from the tag and remove the "v"
              ARTIFACTORY_VERSION="${CIRCLE_TAG//v}"
              # Refuse to continue if the CIRCLE tag doesn't match the poetry config.
              POETRY_VERSION="$(poetry version -s)"
              if [[ "${POETRY_VERSION}" != "${ARTIFACTORY_VERSION}" ]]
              then
                echo "poetry version '${POETRY_VERSION}' does not match artifactory version '${ARTIFACTORY_VERSION}'"
                exit 1
              fi
            else
              # Not a tag and the version was not set in a previous job.
              #
              # Set the pre-release segment according to PEP-440
              # https://peps.python.org/pep-0440/
              # scratch  => "X.Y.Z.dev{CIRCLE_BUILD_NUM}+{COMMIT_HASH}"
              # snapshot => "X.Y.Za{CIRCLE_BUILD_NUM}+{COMMIT_HASH}"
              PRE=".dev"
              if [[ "${CIRCLE_BRANCH}" == main ]]; then PRE="a"; fi
              # Get the x.y.z part of the version from the repo and drop everything else.
              short_semver=$(poetry version -s | sed 's/^\(0\|[1-9]\d*\)\.\(0\|[1-9]\d*\)\.\(0\|[1-9]\d*\).*/\1.\2.\3/g')
              # Construct the PEP-440 compatible version using CircleCI information
              ARTIFACTORY_VERSION="${short_semver}${PRE}${CIRCLE_BUILD_NUM}+${CIRCLE_SHA1:0:7}"
            fi
            poetry version "${ARTIFACTORY_VERSION}"
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Build wheel
          command: poetry build -f wheel
      - store_artifacts:
          path: dist
      - run:
          name: Publish to artifactory
          command: poetry publish -r leapyear-artifactory
workflows:
  build:
    jobs:
      - python/test:
          context: artifactory
          pkg-manager: poetry
          args: -E prospector -E flake8
          pre-install-steps:
            - setup-artifactory
          matrix:
            parameters:
              version: ["3.7", "3.8", "3.9", "3.10"]
      - behave:
          context: artifactory
      - lint:
          context: artifactory
      - deploy:
          context: artifactory
  tag:
    jobs:
      - deploy:
          context: artifactory
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
