version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  lint:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          args: -E all
      - run: poetry run lint --bootstrap
      - run: poetry run lint .
workflows:
  build:
    jobs:
      - python/test:
          name: "test-3.7"
          pkg-manager: poetry
          version: "3.7"
      - python/test:
          name: "test-3.8"
          pkg-manager: poetry
          version: "3.8"
      - python/test:
          name: "test-3.9"
          pkg-manager: poetry
          version: "3.9"
      - python/test:
          name: "test-3.10"
          pkg-manager: poetry
          version: "3.10"
      - lint
