version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  lint:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          args: -E all
      - run: poetry run lint --bootstrap
      - run: poetry run lint .
workflows:
  build:
    jobs:
      - python/test:
          pkg-manager: poetry
      - lint
